// Code generated by goctl. DO NOT EDIT.
// Source: shorturl.proto

package shorturlservice

import (
	"context"

	"github.com/ChenMiaoQiu/go-cloud-disk/rpc/types/rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ConvertRequest  = rpc.ConvertRequest
	ConvertResponse = rpc.ConvertResponse

	ShortUrlService interface {
		// 长链接转短链接方法
		Convert(ctx context.Context, in *ConvertRequest, opts ...grpc.CallOption) (*ConvertResponse, error)
	}

	defaultShortUrlService struct {
		cli zrpc.Client
	}
)

func NewShortUrlService(cli zrpc.Client) ShortUrlService {
	return &defaultShortUrlService{
		cli: cli,
	}
}

// 长链接转短链接方法
func (m *defaultShortUrlService) Convert(ctx context.Context, in *ConvertRequest, opts ...grpc.CallOption) (*ConvertResponse, error) {
	client := rpc.NewShortUrlServiceClient(m.cli.Conn())
	return client.Convert(ctx, in, opts...)
}
